# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7264a8a07ebb464099b801c3d2446485490cf0832eb2ce81532c025d492855d1bf899a9d02b51f08ae3f8042abf541efd116ee9ce0bf9f046d67b900679c14f

test:
  secret_key_base: 2aacb88f771ab313e19f074cca31fef884c343cddb473ffaf40f0c01a0e4a446437a104540ba5793367fdfb79e828540021d3b83eb354a21155802b158b7715a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
